version: '3.3'
services:
  spark-master:
    image: apache/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_MASTER_MEMORY=1G
      - SPARK_MASTER_CORES=1
      - SPARK_EVENTLOG_ENABLED=true
      - SPARK_EVENTLOG_DIR=file:///opt/spark/logs
    ports:
      - "8080:8080"
      - "7077:7077"
    command: >
      bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.master.Master --host spark-master && tail -f /dev/null"
    networks:
      - spark-network
    volumes:
      - ./logs:/opt/spark/logs

  spark-worker-1:
    image: apache/spark:latest
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=1
    ports:
      - "8081:8081"
    command: >
      bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077 && tail -f /dev/null"
    networks:
      - spark-network

  spark-worker-2:
    image: apache/spark:latest
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=1
    ports:
      - "8082:8082"
    command: >
      bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077 && tail -f /dev/null"
    networks:
      - spark-network

  spark-history:
    image: apache/spark:latest
    container_name: spark-history
    environment:
      - SPARK_HISTORY_OPTS=-Dspark.history.fs.logDirectory=/opt/spark/logs
    command: >
      bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.history.HistoryServer && tail -f /dev/null"
    ports:
      - "18080:18080"
    networks:
      - spark-network
    volumes:
      - ./logs:/opt/spark/logs

networks:
  spark-network:
    driver: bridge